sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5tNZvZArVRn5T1zYDzYa
    accessKeySecret: fzAXJMbxm0kpOiiyn99zDUcA3JJQF8
    bucketName: web-tias-lv
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10

  wechat:
    appid: wx5f5eba74269d580c
    secret: 6aeb7fa8e43f1684dbb5bd6acbcd5924
